jpa:
  show-sql: true
  properties:
    hibernate:
      format_sql: true

server:
  port: 8083
  servlet:
    encoding:
      charset: UTF-8

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_management?useSSL=false&serverTimezone=GMT%2b8&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&useUnicode=true&useAffectedRows=true
    username: root
    password: 123456